[tasks.deps]
dependencies = [
    "undeps",
    "docker-compose-up",
    "run-example-server",
]

[tasks.undeps]
dependencies = [
    "stop-example-server",
    "docker-compose-down",
]

[tasks.docker-compose-up]
private = true
command = "docker-compose"
args = ["up", "-d"]

[tasks.docker-compose-down]
private = true
command = "docker-compose"
args = ["down"]

[tasks.ensure-example-server-bin]
private = true
script_runner = "@shell"
script = [
'''
cd example-pitaya-server
go build main.go
'''
]

[tasks.run-example-server]
private = true
dependencies = [ 
    "ensure-example-server-bin", 
    "stop-example-server" 
]
script_runner = "@shell"
script = [
'''
cd example-pitaya-server
./main --port 3251 --type room --frontend=false > output.log 2>&1 & 
echo $! > example-pitaya-server.pid
'''
]

[tasks.stop-example-server]
private = true
script_runner = "@shell"
script = [
'''
cd example-pitaya-server
if [[ -f example-pitaya-server.pid ]]; then
    kill -TERM $(cat example-pitaya-server.pid)
    rm example-pitaya-server.pid
fi
rm -f output.log
'''
]
