/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTOS_BIND_PB_H_INCLUDED
#define PB_PROTOS_BIND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protos_BindMsg {
    pb_callback_t uid;
    pb_callback_t fid;
} protos_BindMsg;


/* Initializer values for message structs */
#define protos_BindMsg_init_default              {{{NULL}, NULL}, {{NULL}, NULL}}
#define protos_BindMsg_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define protos_BindMsg_uid_tag                   1
#define protos_BindMsg_fid_tag                   2

/* Struct field encoding specification for nanopb */
#define protos_BindMsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   uid,               1) \
X(a, CALLBACK, SINGULAR, STRING,   fid,               2)
#define protos_BindMsg_CALLBACK pb_default_field_callback
#define protos_BindMsg_DEFAULT NULL

extern const pb_msgdesc_t protos_BindMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protos_BindMsg_fields &protos_BindMsg_msg

/* Maximum encoded size of messages (where known) */
/* protos_BindMsg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
