/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTOS_DOCMSG_PB_H_INCLUDED
#define PB_PROTOS_DOCMSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protos_DocMsg {
    bool getProtos;
} protos_DocMsg;


/* Initializer values for message structs */
#define protos_DocMsg_init_default               {0}
#define protos_DocMsg_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */
#define protos_DocMsg_getProtos_tag              1

/* Struct field encoding specification for nanopb */
#define protos_DocMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     getProtos,         1)
#define protos_DocMsg_CALLBACK NULL
#define protos_DocMsg_DEFAULT NULL

extern const pb_msgdesc_t protos_DocMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protos_DocMsg_fields &protos_DocMsg_msg

/* Maximum encoded size of messages (where known) */
#define protos_DocMsg_size                       2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
