/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTOS_KICK_PB_H_INCLUDED
#define PB_PROTOS_KICK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protos_KickMsg {
    pb_callback_t userId;
} protos_KickMsg;

typedef struct _protos_KickAnswer {
    bool kicked;
} protos_KickAnswer;


/* Initializer values for message structs */
#define protos_KickMsg_init_default              {{{NULL}, NULL}}
#define protos_KickAnswer_init_default           {0}
#define protos_KickMsg_init_zero                 {{{NULL}, NULL}}
#define protos_KickAnswer_init_zero              {0}

/* Field tags (for use in manual encoding/decoding) */
#define protos_KickMsg_userId_tag                1
#define protos_KickAnswer_kicked_tag             1

/* Struct field encoding specification for nanopb */
#define protos_KickMsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   userId,            1)
#define protos_KickMsg_CALLBACK pb_default_field_callback
#define protos_KickMsg_DEFAULT NULL

#define protos_KickAnswer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     kicked,            1)
#define protos_KickAnswer_CALLBACK NULL
#define protos_KickAnswer_DEFAULT NULL

extern const pb_msgdesc_t protos_KickMsg_msg;
extern const pb_msgdesc_t protos_KickAnswer_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protos_KickMsg_fields &protos_KickMsg_msg
#define protos_KickAnswer_fields &protos_KickAnswer_msg

/* Maximum encoded size of messages (where known) */
/* protos_KickMsg_size depends on runtime parameters */
#define protos_KickAnswer_size                   2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
