/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "kick.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protos_KickMsg, protos_KickMsg, AUTO)


PB_BIND(protos_KickAnswer, protos_KickAnswer, AUTO)



