/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTOS_MSG_PB_H_INCLUDED
#define PB_PROTOS_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _protos_MsgType {
    protos_MsgType_MsgRequest = 0,
    protos_MsgType_MsgNotify = 1,
    protos_MsgType_MsgResponse = 2,
    protos_MsgType_MsgPush = 3
} protos_MsgType;

/* Struct definitions */
typedef struct _protos_Msg {
    uint64_t id;
    pb_callback_t route;
    pb_callback_t data;
    pb_callback_t reply;
    protos_MsgType type;
} protos_Msg;


/* Helper constants for enums */
#define _protos_MsgType_MIN protos_MsgType_MsgRequest
#define _protos_MsgType_MAX protos_MsgType_MsgPush
#define _protos_MsgType_ARRAYSIZE ((protos_MsgType)(protos_MsgType_MsgPush+1))


/* Initializer values for message structs */
#define protos_Msg_init_default                  {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _protos_MsgType_MIN}
#define protos_Msg_init_zero                     {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _protos_MsgType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define protos_Msg_id_tag                        1
#define protos_Msg_route_tag                     2
#define protos_Msg_data_tag                      3
#define protos_Msg_reply_tag                     4
#define protos_Msg_type_tag                      5

/* Struct field encoding specification for nanopb */
#define protos_Msg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   route,             2) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              3) \
X(a, CALLBACK, SINGULAR, STRING,   reply,             4) \
X(a, STATIC,   SINGULAR, UENUM,    type,              5)
#define protos_Msg_CALLBACK pb_default_field_callback
#define protos_Msg_DEFAULT NULL

extern const pb_msgdesc_t protos_Msg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protos_Msg_fields &protos_Msg_msg

/* Maximum encoded size of messages (where known) */
/* protos_Msg_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
