/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTOS_PITAYA_PB_H_INCLUDED
#define PB_PROTOS_PITAYA_PB_H_INCLUDED
#include <pb.h>
#include "request.pb.h"
#include "response.pb.h"
#include "push.pb.h"
#include "bind.pb.h"
#include "kick.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
