/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTOS_PROTODESCRIPTOR_PB_H_INCLUDED
#define PB_PROTOS_PROTODESCRIPTOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protos_ProtoDescriptor {
    pb_callback_t desc;
} protos_ProtoDescriptor;

typedef struct _protos_ProtoDescriptors {
    pb_callback_t desc;
} protos_ProtoDescriptors;

typedef struct _protos_ProtoName {
    pb_callback_t name;
} protos_ProtoName;

typedef struct _protos_ProtoNames {
    pb_callback_t name;
} protos_ProtoNames;


/* Initializer values for message structs */
#define protos_ProtoDescriptor_init_default      {{{NULL}, NULL}}
#define protos_ProtoName_init_default            {{{NULL}, NULL}}
#define protos_ProtoDescriptors_init_default     {{{NULL}, NULL}}
#define protos_ProtoNames_init_default           {{{NULL}, NULL}}
#define protos_ProtoDescriptor_init_zero         {{{NULL}, NULL}}
#define protos_ProtoName_init_zero               {{{NULL}, NULL}}
#define protos_ProtoDescriptors_init_zero        {{{NULL}, NULL}}
#define protos_ProtoNames_init_zero              {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define protos_ProtoDescriptor_desc_tag          1
#define protos_ProtoDescriptors_desc_tag         1
#define protos_ProtoName_name_tag                1
#define protos_ProtoNames_name_tag               1

/* Struct field encoding specification for nanopb */
#define protos_ProtoDescriptor_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    desc,              1)
#define protos_ProtoDescriptor_CALLBACK pb_default_field_callback
#define protos_ProtoDescriptor_DEFAULT NULL

#define protos_ProtoName_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1)
#define protos_ProtoName_CALLBACK pb_default_field_callback
#define protos_ProtoName_DEFAULT NULL

#define protos_ProtoDescriptors_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, BYTES,    desc,              1)
#define protos_ProtoDescriptors_CALLBACK pb_default_field_callback
#define protos_ProtoDescriptors_DEFAULT NULL

#define protos_ProtoNames_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   name,              1)
#define protos_ProtoNames_CALLBACK pb_default_field_callback
#define protos_ProtoNames_DEFAULT NULL

extern const pb_msgdesc_t protos_ProtoDescriptor_msg;
extern const pb_msgdesc_t protos_ProtoName_msg;
extern const pb_msgdesc_t protos_ProtoDescriptors_msg;
extern const pb_msgdesc_t protos_ProtoNames_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protos_ProtoDescriptor_fields &protos_ProtoDescriptor_msg
#define protos_ProtoName_fields &protos_ProtoName_msg
#define protos_ProtoDescriptors_fields &protos_ProtoDescriptors_msg
#define protos_ProtoNames_fields &protos_ProtoNames_msg

/* Maximum encoded size of messages (where known) */
/* protos_ProtoDescriptor_size depends on runtime parameters */
/* protos_ProtoName_size depends on runtime parameters */
/* protos_ProtoDescriptors_size depends on runtime parameters */
/* protos_ProtoNames_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
