/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTOS_PUSH_PB_H_INCLUDED
#define PB_PROTOS_PUSH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protos_Push {
    pb_callback_t route;
    pb_callback_t uid;
    pb_callback_t data;
} protos_Push;


/* Initializer values for message structs */
#define protos_Push_init_default                 {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define protos_Push_init_zero                    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define protos_Push_route_tag                    1
#define protos_Push_uid_tag                      2
#define protos_Push_data_tag                     3

/* Struct field encoding specification for nanopb */
#define protos_Push_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   route,             1) \
X(a, CALLBACK, SINGULAR, STRING,   uid,               2) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              3)
#define protos_Push_CALLBACK pb_default_field_callback
#define protos_Push_DEFAULT NULL

extern const pb_msgdesc_t protos_Push_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protos_Push_fields &protos_Push_msg

/* Maximum encoded size of messages (where known) */
/* protos_Push_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
