/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTOS_REQUEST_PB_H_INCLUDED
#define PB_PROTOS_REQUEST_PB_H_INCLUDED
#include <pb.h>
#include "session.pb.h"
#include "msg.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _protos_RPCType {
    protos_RPCType_Sys = 0,
    protos_RPCType_User = 1
} protos_RPCType;

/* Struct definitions */
typedef struct _protos_Request {
    protos_RPCType type;
    bool has_session;
    protos_Session session;
    bool has_msg;
    protos_Msg msg;
    pb_callback_t frontendID;
    pb_callback_t metadata;
} protos_Request;


/* Helper constants for enums */
#define _protos_RPCType_MIN protos_RPCType_Sys
#define _protos_RPCType_MAX protos_RPCType_User
#define _protos_RPCType_ARRAYSIZE ((protos_RPCType)(protos_RPCType_User+1))


/* Initializer values for message structs */
#define protos_Request_init_default              {_protos_RPCType_MIN, false, protos_Session_init_default, false, protos_Msg_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define protos_Request_init_zero                 {_protos_RPCType_MIN, false, protos_Session_init_zero, false, protos_Msg_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define protos_Request_type_tag                  1
#define protos_Request_session_tag               2
#define protos_Request_msg_tag                   3
#define protos_Request_frontendID_tag            4
#define protos_Request_metadata_tag              5

/* Struct field encoding specification for nanopb */
#define protos_Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  session,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  msg,               3) \
X(a, CALLBACK, SINGULAR, STRING,   frontendID,        4) \
X(a, CALLBACK, SINGULAR, BYTES,    metadata,          5)
#define protos_Request_CALLBACK pb_default_field_callback
#define protos_Request_DEFAULT NULL
#define protos_Request_session_MSGTYPE protos_Session
#define protos_Request_msg_MSGTYPE protos_Msg

extern const pb_msgdesc_t protos_Request_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protos_Request_fields &protos_Request_msg

/* Maximum encoded size of messages (where known) */
/* protos_Request_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
