/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTOS_RESPONSE_PB_H_INCLUDED
#define PB_PROTOS_RESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "error.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protos_Response {
    pb_callback_t data;
    bool has_error;
    protos_Error error;
} protos_Response;


/* Initializer values for message structs */
#define protos_Response_init_default             {{{NULL}, NULL}, false, protos_Error_init_default}
#define protos_Response_init_zero                {{{NULL}, NULL}, false, protos_Error_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define protos_Response_data_tag                 1
#define protos_Response_error_tag                2

/* Struct field encoding specification for nanopb */
#define protos_Response_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  error,             2)
#define protos_Response_CALLBACK pb_default_field_callback
#define protos_Response_DEFAULT NULL
#define protos_Response_error_MSGTYPE protos_Error

extern const pb_msgdesc_t protos_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protos_Response_fields &protos_Response_msg

/* Maximum encoded size of messages (where known) */
/* protos_Response_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
